# Generated by Django 3.2.4 on 2021-06-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='website',
            new_name='site',
        ),
    ]
